AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 80

Metrics/BlockLength:
  Exclude:
    - test/**/*

Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*

Style/StringLiterals:
  EnforcedStyle: single_quotes
